/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_members__get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_members__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Members */
        get: operations["count_members_members_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Member */
        get: operations["get_member_members__member_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_posts__get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_posts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Post
         * @description 게시물 삭제 (관리자 전용).
         */
        delete: operations["delete_post_posts__post_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Post
         * @description 게시물 수정 (관리자 전용).
         */
        patch: operations["update_post_posts__post_id__patch"];
        trace?: never;
    };
    "/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Comments
         * @description 특정 게시글의 댓글 목록 조회
         */
        get: operations["list_comments_comments__get"];
        put?: never;
        /**
         * Create Comment
         * @description 댓글 작성 (회원 또는 관리자)
         */
        post: operations["create_comment_comments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Comment
         * @description 댓글 삭제 (본인 또는 관리자)
         */
        delete: operations["delete_comment_comments__comment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events__get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_events__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rsvp */
        post: operations["create_rsvp_events__event_id__rsvp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rsvps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rsvps */
        get: operations["list_rsvps_rsvps__get"];
        put?: never;
        /** Create Rsvp */
        post: operations["create_rsvp_rsvps__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rsvps/{member_id}/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rsvp */
        get: operations["get_rsvp_rsvps__member_id___event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/member/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Member Login
         * @description 하위호환 멤버 로그인 엔드포인트.
         *
         *     통합 로직으로 세션을 설정하며, 멤버 자격만 검사한다.
         */
        post: operations["member_login_auth_member_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/member/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Member Logout */
        post: operations["member_logout_auth_member_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/member/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Member Me
         * @description 멤버 자기정보: 웹 프론트 타입 정의에 맞춰 email을 반환.
         *
         *     세션에 email이 없을 수 있어 Member 테이블을 조회하여 보강한다.
         */
        get: operations["member_me_auth_member_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/member/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Member Activate
         * @description 멤버 활성화: 서명 토큰 검증 후 Member/MemberAuth를 생성 또는 갱신.
         *
         *     토큰 페이로드 예: {"email": "user@example.com", "name": "User", "cohort": 1}
         *     개발 단계에서는 itsdangerous 서명 토큰을 사용한다.
         */
        post: operations["member_activate_auth_member_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/member/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_auth_member_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 관리자 자기정보(하위호환): 관리자 세션이 있을 때만 200.
         *
         *     통합 세션을 사용하더라도 roles에 'admin'이 있어야 통과한다.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session
         * @description 통합 세션 조회 엔드포인트.
         *
         *     반환 형식: { kind: 'admin'|'member', student_id, email, name, id? }
         *     세션이 없으면 401.
         */
        get: operations["session_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Subscription
         * @description Web Push 구독 저장(idempotent). 동일 endpoint는 갱신 처리.
         */
        post: operations["save_subscription_notifications_subscriptions_post"];
        /** Delete Subscription */
        delete: operations["delete_subscription_notifications_subscriptions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test Push */
        post: operations["send_test_push_notifications_admin_notifications_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Send Logs */
        get: operations["get_send_logs_notifications_admin_notifications_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_notifications_admin_notifications_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/prune-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prune Logs */
        post: operations["prune_logs_notifications_admin_notifications_prune_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/trigger-scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scheduled Notifications
         * @description 예약 알림 수동 트리거 (테스트/복구용).
         */
        post: operations["trigger_scheduled_notifications_notifications_admin_notifications_trigger_scheduled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/admin/notifications/scheduled-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduled Logs
         * @description 예약 발송 내역 조회.
         */
        get: operations["get_scheduled_logs_notifications_admin_notifications_scheduled_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contact */
        post: operations["contact_support_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/admin/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_support_admin_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me__get"];
        /** Update Me */
        put: operations["update_me_me__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Avatar */
        post: operations["upload_avatar_me_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rum/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Vitals
         * @description Ingest Web Vitals from client (no PII, sampling handled client-side).
         *
         *     For now we log as structured events; storage/aggregation can be added later.
         */
        post: operations["ingest_vitals_rum_vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image
         * @description 이미지 파일 업로드.
         *
         *     - 인증된 회원만 접근 가능
         *     - 지원 형식: JPEG, PNG, WebP, GIF
         *     - 최대 크기: 5MB (설정 가능)
         *     - 자동 리사이즈: 1920px 이하로 조정
         *     - GIF: 애니메이션은 첫 프레임만 저장 (정지 이미지로 변환)
         */
        post: operations["upload_image_uploads_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Posts
         * @description 관리자용 게시물 목록 (비공개 포함).
         */
        get: operations["list_admin_posts_admin_posts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Events */
        get: operations["list_admin_events_admin_events__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Admin Event */
        delete: operations["delete_admin_event_admin_events__event_id__delete"];
        options?: never;
        head?: never;
        /** Update Admin Event */
        patch: operations["update_admin_event_admin_events__event_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminEventListResponse */
        AdminEventListResponse: {
            /** Items */
            items: components["schemas"]["EventAdminRead"][];
            /** Total */
            total: number;
        };
        /**
         * AdminPostListResponse
         * @description 관리자 게시물 목록 응답.
         */
        AdminPostListResponse: {
            /** Items */
            items: components["schemas"]["PostRead"][];
            /** Total */
            total: number;
        };
        /** Body_upload_avatar_me_avatar_post */
        Body_upload_avatar_me_avatar_post: {
            /**
             * Avatar
             * Format: binary
             */
            avatar: string;
        };
        /** Body_upload_image_uploads_images_post */
        Body_upload_image_uploads_images_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ChangePasswordPayload */
        ChangePasswordPayload: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CommentCreate */
        CommentCreate: {
            /** Content */
            content: string;
            /** Post Id */
            post_id: number;
            /** Author Id */
            author_id?: number | null;
        };
        /** CommentRead */
        CommentRead: {
            /** Content */
            content: string;
            /** Id */
            id: number;
            /** Post Id */
            post_id: number;
            /** Author Id */
            author_id: number;
            /** Author Name */
            author_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ContactPayload */
        ContactPayload: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Contact */
            contact?: string | null;
            /** Hp */
            hp?: string | null;
        };
        /**
         * EventAdminRead
         * @description 관리자 행사 목록 전용 응답 (참여 집계 포함).
         */
        EventAdminRead: {
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Location */
            location: string;
            /** Capacity */
            capacity: number;
            /** Id */
            id: number;
            rsvp_counts: components["schemas"]["RSVPCounts"];
        };
        /** EventCreate */
        EventCreate: {
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Location */
            location: string;
            /** Capacity */
            capacity: number;
        };
        /** EventRead */
        EventRead: {
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Location */
            location: string;
            /** Capacity */
            capacity: number;
            /** Id */
            id: number;
        };
        /** EventUpdate */
        EventUpdate: {
            /** Title */
            title?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location?: string | null;
            /** Capacity */
            capacity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageUploadResponse
         * @description 이미지 업로드 응답.
         */
        ImageUploadResponse: {
            /** Url */
            url: string;
            /** Filename */
            filename: string;
        };
        /** LoginPayload */
        LoginPayload: {
            /** Student Id */
            student_id: string;
            /** Password */
            password: string;
        };
        /** MemberActivatePayload */
        MemberActivatePayload: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** MemberCount */
        MemberCount: {
            /** Count */
            count: number;
        };
        /** MemberCreate */
        MemberCreate: {
            /** Student Id */
            student_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Cohort */
            cohort: number;
            /** Major */
            major?: string | null;
            /**
             * Roles
             * @default member
             */
            roles: string;
            /**
             * Visibility
             * @default all
             * @enum {string}
             */
            visibility: "all" | "cohort" | "private";
            /** Birth Date */
            birth_date?: string | null;
            /** Birth Lunar */
            birth_lunar?: boolean | null;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Department */
            department?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Phone */
            company_phone?: string | null;
            /** Addr Personal */
            addr_personal?: string | null;
            /** Addr Company */
            addr_company?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /** MemberLoginPayload */
        MemberLoginPayload: {
            /** Student Id */
            student_id: string;
            /** Password */
            password: string;
        };
        /** MemberRead */
        MemberRead: {
            /** Student Id */
            student_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Cohort */
            cohort: number;
            /** Major */
            major?: string | null;
            /**
             * Roles
             * @default member
             */
            roles: string;
            /**
             * Visibility
             * @default all
             * @enum {string}
             */
            visibility: "all" | "cohort" | "private";
            /** Birth Date */
            birth_date?: string | null;
            /** Birth Lunar */
            birth_lunar?: boolean | null;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Department */
            department?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Phone */
            company_phone?: string | null;
            /** Addr Personal */
            addr_personal?: string | null;
            /** Addr Company */
            addr_company?: string | null;
            /** Industry */
            industry?: string | null;
            /** Id */
            id: number;
            /** Avatar Url */
            readonly avatar_url: string | null;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Name */
            name?: string | null;
            /** Major */
            major?: string | null;
            /** Visibility */
            visibility?: ("all" | "cohort" | "private") | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Birth Lunar */
            birth_lunar?: boolean | null;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Department */
            department?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Company Phone */
            company_phone?: string | null;
            /** Addr Personal */
            addr_personal?: string | null;
            /** Addr Company */
            addr_company?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /** NotificationStats */
        NotificationStats: {
            /** Active Subscriptions */
            active_subscriptions: number;
            /** Recent Accepted */
            recent_accepted: number;
            /** Recent Failed */
            recent_failed: number;
            /** Encryption Enabled */
            encryption_enabled: boolean;
            /** Range */
            range?: string | null;
            /** Failed 404 */
            failed_404?: number | null;
            /** Failed 410 */
            failed_410?: number | null;
            /** Failed Other */
            failed_other?: number | null;
        };
        /** PostCreate */
        PostCreate: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Published At */
            published_at?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Cover Image */
            cover_image?: string | null;
            /** Images */
            images?: string[] | null;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /** Author Id */
            author_id?: number | null;
        };
        /** PostRead */
        PostRead: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Published At */
            published_at?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Cover Image */
            cover_image?: string | null;
            /** Images */
            images?: string[] | null;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /** Id */
            id: number;
            /** Author Id */
            author_id: number;
            /** Author Name */
            author_name?: string | null;
            /**
             * Comment Count
             * @default 0
             */
            comment_count: number;
        };
        /**
         * PostUpdate
         * @description 게시물 수정용 스키마 (부분 업데이트).
         *
         *     필드를 요청에 포함하지 않으면 해당 필드는 변경되지 않음.
         *     포함된 필드는 None 포함 그대로 DB에 반영됨.
         */
        PostUpdate: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Category */
            category?: string | null;
            /** Pinned */
            pinned?: boolean | null;
            /**
             * Published At
             * @description 미포함→변경없음, 값→발행일시, null→비공개
             */
            published_at?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /** Images */
            images?: string[] | null;
            /**
             * Unpublish
             * @description True면 published_at을 None으로 강제 설정 (비공개 전환)
             * @default false
             */
            unpublish: boolean;
        };
        /** PruneLogsPayload */
        PruneLogsPayload: {
            /**
             * Older Than Days
             * @default 30
             */
            older_than_days: number;
        };
        /**
         * RSVPCounts
         * @description 행사별 참여 현황 집계.
         */
        RSVPCounts: {
            /**
             * Going
             * @default 0
             */
            going: number;
            /**
             * Waitlist
             * @default 0
             */
            waitlist: number;
            /**
             * Cancel
             * @default 0
             */
            cancel: number;
        };
        /** RSVPCreate */
        RSVPCreate: {
            /** Member Id */
            member_id: number;
            /** Event Id */
            event_id: number;
            /**
             * Status
             * @default going
             * @enum {string}
             */
            status: "going" | "waitlist" | "cancel";
        };
        /** RSVPRead */
        RSVPRead: {
            /** Member Id */
            member_id: number;
            /** Event Id */
            event_id: number;
            /**
             * Status
             * @default going
             * @enum {string}
             */
            status: "going" | "waitlist" | "cancel";
        };
        /** RSVPStatusUpdate */
        RSVPStatusUpdate: {
            /** Member Id */
            member_id: number;
            /**
             * Status
             * @default going
             * @enum {string}
             */
            status: "going" | "waitlist" | "cancel";
        };
        /** ScheduledLogRead */
        ScheduledLogRead: {
            /** Id */
            id: number;
            /** Event Id */
            event_id: number;
            /** D Type */
            d_type: string;
            /** Scheduled At */
            scheduled_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Accepted Count */
            accepted_count: number;
            /** Failed Count */
            failed_count: number;
            /** Status */
            status: string;
        };
        /** SendLogRead */
        SendLogRead: {
            /** Created At */
            created_at: string;
            /** Ok */
            ok: boolean;
            /** Status Code */
            status_code: number | null;
            /** Endpoint Tail */
            endpoint_tail: string | null;
        };
        /** SubscriptionPayload */
        SubscriptionPayload: {
            /**
             * Endpoint
             * Format: uri
             */
            endpoint: string;
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
            /** Ua */
            ua?: string | null;
        };
        /** TestPushPayload */
        TestPushPayload: {
            /**
             * Title
             * @default 테스트 알림
             */
            title: string;
            /**
             * Body
             * @default 웹 푸시 경로 연결 확인
             */
            body: string;
            /** Url */
            url?: string | null;
        };
        /** TicketRead */
        TicketRead: {
            /** Created At */
            created_at: string;
            /** Member Email */
            member_email: string | null;
            /** Subject */
            subject: string;
            /** Contact */
            contact: string | null;
            /** Client Ip */
            client_ip: string | null;
        };
        /** TriggerScheduledPayload */
        TriggerScheduledPayload: {
            /** Target Date */
            target_date?: string | null;
        };
        /** UnsubscribePayload */
        UnsubscribePayload: {
            /**
             * Endpoint
             * Format: uri
             */
            endpoint: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebVitalEvent */
        WebVitalEvent: {
            /**
             * Name
             * @description Metric name: LCP/INP/CLS/FCP/TTFB
             */
            name: string;
            /**
             * Id
             * @description Unique ID per metric instance
             */
            id: string;
            /**
             * Value
             * @description Metric value
             */
            value: number;
            /**
             * Delta
             * @description Change since last report
             */
            delta?: number | null;
            /**
             * Rating
             * @description good|needs-improvement|poor
             */
            rating?: string | null;
            /**
             * Path
             * @description Page path
             */
            path?: string | null;
            /**
             * Navtype
             * @description Navigation type
             */
            navType?: string | null;
            /**
             * Device
             * @description mobile|desktop (heuristic)
             */
            device?: string | null;
            /**
             * Commit
             * @description Client commit sha
             */
            commit?: string | null;
            /**
             * Ts
             * @description Client timestamp (ms)
             */
            ts?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_members_members__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                cohort?: number | null;
                major?: string | null;
                company?: string | null;
                industry?: string | null;
                region?: string | null;
                job_title?: string | null;
                sort?: "recent" | "cohort_desc" | "cohort_asc" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_member_members__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_members_members_count_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                cohort?: number | null;
                major?: string | null;
                company?: string | null;
                industry?: string | null;
                region?: string | null;
                job_title?: string | null;
                sort?: "recent" | "cohort_desc" | "cohort_asc" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_members__member_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_posts__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_posts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_comments__get: {
        parameters: {
            query: {
                post_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_comments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comment_comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_events__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_events__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rsvp_events__event_id__rsvp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RSVPStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSVPRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rsvps_rsvps__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSVPRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rsvp_rsvps__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RSVPCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSVPRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rsvp_rsvps__member_id___event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSVPRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_login_auth_member_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberLoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_logout_auth_member_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    member_me_auth_member_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    member_activate_auth_member_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberActivatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_member_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | number;
                    };
                };
            };
        };
    };
    session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    save_subscription_notifications_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_notifications_subscriptions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_push_notifications_admin_notifications_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestPushPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_send_logs_notifications_admin_notifications_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_notifications_admin_notifications_stats_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prune_logs_notifications_admin_notifications_prune_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PruneLogsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scheduled_notifications_notifications_admin_notifications_trigger_scheduled_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerScheduledPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduled_logs_notifications_admin_notifications_scheduled_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contact_support_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_support_admin_tickets_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
        };
    };
    update_me_me__put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_avatar_me_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_vitals_rum_vitals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebVitalEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_uploads_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_uploads_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_posts_admin_posts__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string | null;
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_events_admin_events__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                status?: ("upcoming" | "ongoing" | "ended") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_admin_event_admin_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_admin_event_admin_events__event_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
