export type ClassPresident = {
  cohort: number;
  name: string | null;
  workplace: string | null;
};

export const CLASS_PRESIDENT_SOURCE = 'https://econ.sogang.ac.kr/econ/1699/subview.do';

export const CLASS_PRESIDENTS: readonly ClassPresident[] = [
  { cohort: 1, name: '송성기', workplace: '한일기술협력재단' },
  { cohort: 2, name: '라윤정', workplace: '메트릭스' },
  { cohort: 3, name: '정안준', workplace: '농협중앙회 부장' },
  { cohort: 4, name: '김완기', workplace: '서강대 기술경영전문대학원 교수' },
  { cohort: 5, name: '최봉준', workplace: '신한은행 지점장' },
  { cohort: 6, name: '은항재', workplace: '국민은행' },
  { cohort: 7, name: '최종성', workplace: '전 제일경제통계컨설팅 대표' },
  { cohort: 8, name: '한희성', workplace: '전 국민은행 과장' },
  { cohort: 9, name: '최삼열', workplace: '한국외환은행' },
  { cohort: 10, name: '김주한', workplace: '전 중앙신용정보 감사' },
  { cohort: 11, name: '박인규', workplace: '창대산업 대표' },
  { cohort: 12, name: '김종생', workplace: '한국외환은행' },
  { cohort: 13, name: '고상근', workplace: '국회 사무처 기획조정실 서기관' },
  { cohort: 14, name: '김흥근', workplace: '화물차공제조합인천시지부장' },
  { cohort: 15, name: '정재동', workplace: '유앤미솔루션 대표' },
  { cohort: 16, name: '김주홍', workplace: '라이브카페 미몽대표' },
  { cohort: 17, name: '유동열', workplace: '회룡건설' },
  { cohort: 18, name: '박성용', workplace: '대일기업평가원 이사' },
  { cohort: 19, name: '이영수', workplace: '전 한국정보통신영업1부 부서장' },
  { cohort: 20, name: '김추곤', workplace: '서강대 시스템운영팀 차장' },
  { cohort: 21, name: '장태성', workplace: '국회사무처 문광위 입법조사관실' },
  { cohort: 22, name: '이상웅', workplace: '한양증권 이사' },
  { cohort: 23, name: '장인환', workplace: '수인교역' },
  { cohort: 24, name: '연준흠', workplace: 'INS 총괄이사' },
  { cohort: 25, name: '이문희', workplace: '오버랜드스토리지코리아 영업팀장' },
  { cohort: 26, name: '서혜경', workplace: '한국씨티은행 전략영업부 팀장' },
  { cohort: 27, name: '안태석', workplace: '서울조달청' },
  { cohort: 28, name: '표의정', workplace: 'LG생건' },
  { cohort: 29, name: '장인범', workplace: '대신증권' },
  { cohort: 30, name: '전정환', workplace: '국민연금' },
  { cohort: 31, name: null, workplace: null },
  { cohort: 32, name: '백광현', workplace: '두산IND' },
  { cohort: 33, name: null, workplace: null },
  { cohort: 34, name: '황보우', workplace: 'K＆P인베스트' },
  { cohort: 35, name: '고창훈', workplace: '동양생명' },
  { cohort: 36, name: '나종율', workplace: '경보제약' },
  { cohort: 37, name: '박동수', workplace: '기업데이터' },
  { cohort: 38, name: '이승민', workplace: '우리은행' },
  { cohort: 39, name: '강현호', workplace: '흥국생명' },
  { cohort: 40, name: '박상협', workplace: '대한간호협회' },
  { cohort: 41, name: '최중석', workplace: '에프앤가이드' },
  { cohort: 42, name: '김문수', workplace: '화이텍기술투자' },
  { cohort: 43, name: '박문수', workplace: '인주새마을금고' },
  { cohort: 44, name: '이환선', workplace: '에셋플러스자산운용' },
  { cohort: 45, name: '이승현', workplace: '에프앤가이드' },
  { cohort: 46, name: '이민영', workplace: '동원홈푸드' },
  { cohort: 47, name: '허민철', workplace: '트라움자원' },
  { cohort: 48, name: '김형중', workplace: '삼성전자' },
  { cohort: 49, name: '김동근', workplace: '유진투자증권' },
  { cohort: 50, name: '이승현', workplace: '유진투자증권' },
  { cohort: 51, name: '류호경', workplace: '신용회복위원회' },
  { cohort: 52, name: '장재원', workplace: '대화감정법인' },
  { cohort: 53, name: '최창선', workplace: '데이원컴퍼니' },
  { cohort: 54, name: '김박사', workplace: '다우기술' },
  { cohort: 55, name: '황승환', workplace: '라이프앤바이오' },
  { cohort: 56, name: '정경호', workplace: null },
  { cohort: 57, name: '이윤권', workplace: '위펀' },
  { cohort: 58, name: '조슬기', workplace: 'SBS BIZ' },
  { cohort: 59, name: '황재호', workplace: '(주)포블게이트' },
  { cohort: 60, name: '김경준', workplace: '신한은행' },
  { cohort: 61, name: '고유한', workplace: '트러스톤자산운용(주)' },
  { cohort: 62, name: '김명진', workplace: '전 소속 LG display' },
  { cohort: 63, name: '진현수', workplace: '한스프라임자산운용(주)' },
  { cohort: 64, name: '이동협', workplace: '에이치엘클레무브' },
  { cohort: 65, name: '김정선', workplace: 'NH투자증권' },
  { cohort: 66, name: '이현표', workplace: '한비감정평가사합동사무소' },
  { cohort: 67, name: '김수영', workplace: 'CBS 보도국' },
  { cohort: 68, name: '오송현', workplace: '롯데손해보험' },
  { cohort: 69, name: '김정룡', workplace: '저축은행중앙회' },
  { cohort: 70, name: '박세영', workplace: null },
  { cohort: 71, name: '박유민', workplace: null }
] as const;
