"""Remove email field from MemberAuth

Revision ID: 34e6be759c7d
Revises: f2b5a9b1cafe
Create Date: 2025-10-23 23:37:11.833021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e6be759c7d'
down_revision = 'f2b5a9b1cafe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###