"""add_student_id_to_admin_user

Revision ID: 72d4bb051add
Revises: 3c1fa6c678e1
Create Date: 2025-10-23 20:03:05.282403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d4bb051add'
down_revision = '3c1fa6c678e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """admin_users.student_id 추가 (SQLite 호환 포함).

    - Postgres: 기존 스크립트 흐름
    - SQLite: substr/instr 사용 + batch_alter_table로 NOT NULL/nullable 변경
    """
    bind = op.get_bind()
    dialect = bind.dialect.name

    # 1) 컬럼 추가
    op.add_column('admin_users', sa.Column('student_id', sa.String(length=20), nullable=True))

    # 2) 기존 데이터 채우기
    if dialect == 'postgresql':
        op.execute(
            "UPDATE admin_users SET student_id = 'admin_' || substring(email, 1, position('@' in email) - 1) "
            "WHERE student_id IS NULL"
        )
        # NOT NULL + 인덱스 + email nullable
        op.alter_column('admin_users', 'student_id', nullable=False)
        op.create_index(op.f('ix_admin_users_student_id'), 'admin_users', ['student_id'], unique=True)
        op.alter_column('admin_users', 'email', existing_type=sa.VARCHAR(length=255), nullable=True)
    else:
        # SQLite 분기
        op.execute(
            sa.text(
                "UPDATE admin_users "
                "SET student_id = 'admin_' || substr(email, 1, instr(email, '@') - 1) "
                "WHERE student_id IS NULL"
            )
        )
        with op.batch_alter_table('admin_users') as batch_op:
            batch_op.alter_column('student_id', existing_type=sa.String(length=20), nullable=False)
            batch_op.alter_column('email', existing_type=sa.VARCHAR(length=255), nullable=True)
        op.create_index('ix_admin_users_student_id', 'admin_users', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_users_student_id'), table_name='admin_users')
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('admin_users', 'student_id')
    # ### end Alembic commands ###
