"""add scheduled_notification_logs table

Revision ID: a3d573e4dad9
Revises: e2143fa9dd96
Create Date: 2025-12-04 11:49:11.239434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d573e4dad9'
down_revision = 'e2143fa9dd96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('d_type', sa.String(length=8), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_notification_event_dtype', 'scheduled_notification_logs', ['event_id', 'd_type'], unique=True)
    op.create_index(op.f('ix_scheduled_notification_logs_event_id'), 'scheduled_notification_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_notification_logs_event_id'), table_name='scheduled_notification_logs')
    op.drop_index('ix_scheduled_notification_event_dtype', table_name='scheduled_notification_logs')
    op.drop_table('scheduled_notification_logs')
    # ### end Alembic commands ###