"""add view_count to posts

Revision ID: b0defb6bab2f
Revises: 76f24ccecb58
Create Date: 2025-11-12 13:58:51.045117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0defb6bab2f'
down_revision = '76f24ccecb58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'view_count')
    # ### end Alembic commands ###