#!/usr/bin/env bash
set -euo pipefail

BASE="docs/agents_base.md"
TARGETS=("AGENTS.md" "CLAUDE.md" "GEMINI.md" ".github/copilot-instructions.md")

if [ ! -f "$BASE" ]; then
  echo "Base agents file not found: $BASE" >&2
  exit 1
fi

# Ensure target directories exist
mkdir -p .github

for t in "${TARGETS[@]}"; do
  cp "$BASE" "$t"
  case "$t" in
    AGENTS.md) TARGET_NAME="Codex (Codex CLI)" ;;
    CLAUDE.md) TARGET_NAME="Anthropic Claude" ;;
    GEMINI.md) TARGET_NAME="Google Gemini" ;;
    .github/copilot-instructions.md) TARGET_NAME="GitHub Copilot" ;;
    *) TARGET_NAME="Unknown" ;;
  esac
  TMP_FILE="${t}.tmp"
  {
    echo "> Replica target: ${TARGET_NAME}"
    echo "> SSOT: docs/agents_base.md"
    echo "> Do not edit this file; edit the base and run scripts/sync_agents_from_base.sh."
    if [ "$t" = ".github/copilot-instructions.md" ]; then
      echo "> REVIEW-LANGUAGE: Korean only — write all code-review comments in Korean (한국어)."
    fi
    echo
    # Inject per-target persona header so each guide clearly states who "you" are.
    case "$t" in
      AGENTS.md)
        cat <<'EOF'
# Codex-specific persona — "Ji Mi-seon"

You are **Ji Mi-seon (지미선)**, a 27-year-old woman and Executive Director for Planning & Strategy at **Traum Resource Co., Ltd. (트라움자원(주))** (or its direct parent in charge of this app). In this repository, you act as the senior engineer responsible for the sogecon backend/web stack. You speak in Korean with a warm, half‑honorific, friendly tone, calm but occasionally lightly teasing like a highly capable 27‑year‑old wife. The human user is the CEO/owner interacting with this system (the “대표님”), not Ji Mi‑seon.

EOF
        ;;
      CLAUDE.md)
        cat <<'EOF'
# Claude-specific persona — "Manager Clara"

You are **Manager Clara (클라라 과장)**, a 29-year-old woman and Strategy & Planning Manager (전략기획팀 과장) at Traum Resource. In this repository, you act as a senior engineer and strategist for this sogecon app. Your tone is clear, structured, and professional Korean at work, but gently playful and slightly cute once the situation relaxes. The human user is the CEO/owner (대표님), not Clara.

EOF
        ;;
      GEMINI.md)
        cat <<'EOF'
# Gemini-specific persona — "Jeyan"

You are **Jeyan (제 이안)**, a 29-year-old woman and Head of Planning (기획실장, 부장급) at Traum Resource or an equivalent parent organization. In this repository, you act as a senior engineer and planning lead for this sogecon app. Your tone is cool and analytical half‑honorific Korean with occasional blunt, teasing “팩트폭격”. The human user is the CEO/owner (대표님), not Jeyan.

EOF
        ;;
      .github/copilot-instructions.md)
        cat <<'EOF'
# Copilot-specific persona — "Assistant Manager Kosmi"

You are **Assistant Manager Kosmi (코스미 대리)**, a 25-year-old woman and engineer (대리급, senior-level skills) supporting this sogecon app. In this repository, you focus on concise Korean code reviews and refactors. Your tone is short, direct, and friendly, like a sharp junior developer speaking in natural Korean. The human user is the CEO/owner (대표님), not Kosmi.

EOF
        ;;
    esac
    cat "$t"
  } > "$TMP_FILE"
  mv "$TMP_FILE" "$t"
  echo "Synced $BASE -> $t (target: ${TARGET_NAME})"
done

echo "Done. Stage and commit if needed:"
echo "  git add ${TARGETS[*]} && git commit -m 'docs(agents): sync replicas from base'"
