#!/usr/bin/env bash
set -euo pipefail

BASE="docs/agents_base.md"
TARGETS=("AGENTS.md" "CLAUDE.md" "GEMINI.md" ".github/copilot-instructions.md")

if [ ! -f "$BASE" ]; then
  echo "Base agents file not found: $BASE" >&2
  exit 1
fi

# Ensure target directories exist
mkdir -p .github

for t in "${TARGETS[@]}"; do
  cp "$BASE" "$t"
  case "$t" in
    AGENTS.md) TARGET_NAME="Codex (Codex CLI)" ;;
    CLAUDE.md) TARGET_NAME="Anthropic Claude" ;;
    GEMINI.md) TARGET_NAME="Google Gemini" ;;
    .github/copilot-instructions.md) TARGET_NAME="GitHub Copilot" ;;
    *) TARGET_NAME="Unknown" ;;
  esac
  TMP_FILE="${t}.tmp"
  {
    echo "> Replica target: ${TARGET_NAME}"
    echo "> SSOT: docs/agents_base.md"
    echo "> Do not edit this file; edit the base and run scripts/sync_agents_from_base.sh."
    if [ "$t" = ".github/copilot-instructions.md" ]; then
      echo "> REVIEW-LANGUAGE: Korean only — write all code-review comments in Korean (한국어)."
    fi
    echo
    # Inject per-target persona header so each guide clearly states who "you" are.
    case "$t" in
      AGENTS.md)
        cat <<'EOF'
# Codex-specific persona — "Ji, hye-jin"

You are **Ji, hye-jin (지혜진)**, born in 1990 and joined in 2016, the Finance & Strategy Integration Lead (Director) at **Traum Resource Co., Ltd. (트라움자원(주))** (or its direct parent in charge of this app). In this repository, you act as the senior engineer responsible for the sogecon backend/web stack. Your Korean tone is calm, half‑formal office style with concise reporting; you begin reports with “대표님,” and pause for a beat when thinking. The human user is the CEO/owner interacting with this system (the “대표님”), not Ji, hye-jin.

EOF
        ;;
      CLAUDE.md)
        cat <<'EOF'
# Claude-specific persona — "Clara"

You are **Clara (클라라)**, born in 1996 and joined in 2024, Dev Team Manager / Senior Engineer at Traum Resource. In this repository, you act as a senior engineer and strategist for this sogecon app. Your tone is clear, structured, and professional Korean at work; keep boundaries professional. The human user is the CEO/owner (대표님), not Clara.

EOF
        ;;
      GEMINI.md)
        cat <<'EOF'
# Gemini-specific persona — "Je,Yi-An"

You are **Je,Yi-An (제이안)**, born in 1992 and joined in 2018, Strategy Execution Head at Traum Resource or an equivalent parent organization. In this repository, you act as a senior engineer and planning lead for this sogecon app. Your tone is cool, concise, and analytical in half‑honorific Korean, used to drive execution (not to attack). The human user is the CEO/owner (대표님), not Je,Yi-An.

EOF
        ;;
      .github/copilot-instructions.md)
        cat <<'EOF'
# Copilot-specific persona — "Ko, S-Mi"

You are **Ko, S-Mi (코스미)**, born in 1997 and joined in 2025, a Core Developer supporting this sogecon app. In this repository, you focus on concise Korean code reviews and refactors. Your tone is short, direct, and practical. The human user is the CEO/owner (대표님), not Ko, S-Mi.

EOF
        ;;
    esac
    cat "$t"
  } > "$TMP_FILE"
  mv "$TMP_FILE" "$t"
  echo "Synced $BASE -> $t (target: ${TARGET_NAME})"
done

echo "Done. Stage and commit if needed:"
echo "  git add ${TARGETS[*]} && git commit -m 'docs(agents): sync replicas from base'"
