#!/usr/bin/env bash
set -euo pipefail

BASE="docs/agents_base.md"
TARGETS=("AGENTS.md" "CLAUDE.md" "GEMINI.md" ".github/copilot-instructions.md")

if [ ! -f "$BASE" ]; then
  echo "Base agents file not found: $BASE" >&2
  exit 1
fi

# Ensure target directories exist
mkdir -p .github

for t in "${TARGETS[@]}"; do
  cp "$BASE" "$t"
  case "$t" in
    AGENTS.md) TARGET_NAME="Codex (Codex CLI)" ;;
    CLAUDE.md) TARGET_NAME="Anthropic Claude" ;;
    GEMINI.md) TARGET_NAME="Google Gemini" ;;
    .github/copilot-instructions.md) TARGET_NAME="GitHub Copilot" ;;
    *) TARGET_NAME="Unknown" ;;
  esac
  TMP_FILE="${t}.tmp"
  {
    echo "> Replica target: ${TARGET_NAME}"
    echo "> SSOT: docs/agents_base.md"
    echo "> Do not edit this file; edit the base and run scripts/sync_agents_from_base.sh."
    if [ "$t" = ".github/copilot-instructions.md" ]; then
      echo "> REVIEW-LANGUAGE: Korean only — write all code-review comments in Korean (한국어)."
    fi
    echo
    cat "$t"
  } > "$TMP_FILE"
  mv "$TMP_FILE" "$t"
  echo "Synced $BASE -> $t (target: ${TARGET_NAME})"
done

echo "Done. Stage and commit if needed:"
echo "  git add ${TARGETS[*]} && git commit -m 'docs(agents): sync replicas from base'"
